### ISSUE TITLE
Is there any source code?

### ISSUE THREAD

**Issue by username1565** [charygao/KMSpico_v10.2.0#3]
Is this open source, like this: https://github.com/Wind4/vlmcsd
If yes, is there any source code? Can you publish this?
If not, how to decompile, and disassembly, and deobfuscate this from exe?

**Comment by charygao** [comment]
> Is this open source, like this: https://github.com/Wind4/vlmcsd
> If yes, is there any source code? Can you publish this?
> If not, how to decompile, and disassembly, and deobfuscate this from exe?

sorry,I copied from others.

**Comment by username1565** [comment]
Hm... Ok.
I think, will be better to don't close this program when "nothing to do",
and keep this as KMS-server, on 0.0.0.0:1688.
Maybe this is possible to write it inside the compiled binary-file,
but I don't know how to do it.
